#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef SENSORBIOBTSDK_SWIFT_H
#define SENSORBIOBTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SensorBioBTSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SensorBioBTSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(uint8_t, DeviceConfigurationPPGModeEnableType, open) {
  DeviceConfigurationPPGModeEnableTypePassive = 0x00,
  DeviceConfigurationPPGModeEnableTypeBLE = 0x01,
  DeviceConfigurationPPGModeEnableTypeTimed = 0x02,
  DeviceConfigurationPPGModeEnableTypeSleep = 0x03,
  DeviceConfigurationPPGModeEnableTypeButton = 0x04,
  DeviceConfigurationPPGModeEnableTypeWired = 0x05,
  DeviceConfigurationPPGModeEnableTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, DeviceConfigurationStateType, open) {
  DeviceConfigurationStateTypePassive = 0x00,
  DeviceConfigurationStateTypeTriggered = 0x01,
  DeviceConfigurationStateTypeActive = 0x02,
  DeviceConfigurationStateTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, DeviceParameterType, open) {
  DeviceParameterTypeSerialNumber = 0x01,
  DeviceParameterTypeChargeCycle = 0x02,
  DeviceParameterTypeAdvertisingInterval = 0x03,
  DeviceParameterTypeCanLogDiagnostics = 0x04,
  DeviceParameterTypeLedBrightness = 0x09,
  DeviceParameterTypeHeartBeatTime = 0x0A,
  DeviceParameterTypeDataStorage = 0x0B,
  DeviceParameterTypeChipID = 0x0C,
  DeviceParameterTypePspKey = 0x0D,
  DeviceParameterTypeButtonConfig = 0x15,
  DeviceParameterTypePassiveSensorConfig = 0x16,
  DeviceParameterTypeTriggerSensorConfig = 0x17,
  DeviceParameterTypeActiveSensorConfig = 0x18,
  DeviceParameterTypePassiveCaptureConfig = 0x19,
  DeviceParameterTypeTriggerCaptureConfig = 0x1A,
  DeviceParameterTypeActiveCaptureConfig = 0x1B,
};

typedef SWIFT_ENUM(uint8_t, HapticMotorType, open) {
  HapticMotorTypeOn = 0x00,
  HapticMotorTypePulse = 0x01,
  HapticMotorTypeUnknown = 0xff,
};

@class SB_Device;
SWIFT_CLASS("_TtC14SensorBioBTSDK8SB_BTSDK")
@interface SB_BTSDK : NSObject
@property (nonatomic, readonly) BOOL bluetoothAvailable;
@property (nonatomic, readonly, copy) NSArray<SB_Device *> * _Nonnull discoveredDevices;
@property (nonatomic, readonly, copy) NSArray<SB_Device *> * _Nonnull connectedDevices;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, sensrDeviceType, open) {
  sensrDeviceTypeAlter = 3,
  sensrDeviceTypeSensr = 4,
  sensrDeviceTypeUnknown = 99,
};

@class CBCentralManager;
@class CBPeripheral;
@class NSString;
@class NSNumber;
@interface SB_BTSDK (SWIFT_EXTENSION(SensorBioBTSDK)) <CBCentralManagerDelegate>
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
@end

SWIFT_CLASS("_TtC14SensorBioBTSDK9SB_Device")
@interface SB_Device : NSObject
@property (nonatomic) enum sensrDeviceType type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CBService;
@class CBL2CAPChannel;
@class CBDescriptor;
@class CBCharacteristic;
@interface SB_Device (SWIFT_EXTENSION(SensorBioBTSDK)) <CBPeripheralDelegate>
- (void)peripheralDidUpdateName:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheralIsReadyToSendWriteWithoutResponse:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didModifyServices:(NSArray<CBService *> * _Nonnull)invalidatedServices;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didReadRSSI:(NSNumber * _Nonnull)RSSI error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didOpenL2CAPChannel:(CBL2CAPChannel * _Nullable)channel error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverDescriptorsForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverIncludedServicesForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end

typedef SWIFT_ENUM(uint8_t, algorithmPacketType, open) {
  algorithmPacketTypePhilipsSleep = 0x2f,
  algorithmPacketTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, alterManufacturingTestType, open) {
  alterManufacturingTestTypeFlashIF = 0x01,
  alterManufacturingTestTypeFlashArray = 0x02,
  alterManufacturingTestTypeSpectralIF = 0x03,
  alterManufacturingTestTypeSpectralFIFO = 0x04,
  alterManufacturingTestTypeImuIF = 0x05,
  alterManufacturingTestTypeImuFIFO = 0x06,
  alterManufacturingTestTypeLed = 0x07,
  alterManufacturingTestTypeMotor = 0x08,
  alterManufacturingTestTypePpgUserTriggerButton = 0x09,
  alterManufacturingTestTypeSpectralLEDS = 0x0A,
  alterManufacturingTestTypeImuSelfTest = 0x0B,
  alterManufacturingTestTypeSpectralLEDLeakage = 0x0C,
  alterManufacturingTestTypeImuNoiseFloor = 0x0D,
  alterManufacturingTestTypeTemp = 0x0E,
  alterManufacturingTestTypePmic = 0x0F,
  alterManufacturingTestTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, bookendType, open) {
  bookendTypeActivity = 0x00,
  bookendTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, buttonCommandType, open) {
  buttonCommandTypeNone = 0x00,
  buttonCommandTypeShowBattery = 0x01,
  buttonCommandTypeAdvertiseShowConnection = 0x02,
  buttonCommandTypeHrmAdvertiseToggleActivity = 0x03,
  buttonCommandTypeShutDown = 0x04,
  buttonCommandTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, buttonTapType, open) {
  buttonTapTypeSingle = 0x00,
  buttonTapTypeDouble = 0x01,
  buttonTapTypeTriple = 0x02,
  buttonTapTypeLong = 0x03,
  buttonTapTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, diagnosticType, open) {
  diagnosticTypeSleep = 0x00,
  diagnosticTypePpgBroken = 0x01,
  diagnosticTypePmicStatus = 0x02,
  diagnosticTypeAlgorithm = 0x03,
  diagnosticTypeRotation = 0x04,
  diagnosticTypePmicWatchdog = 0x05,
  diagnosticTypeBluetoothPacket = 0xfe,
  diagnosticTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, eventType, open) {
  eventTypePpgUserTriggerButton = 0x00,
  eventTypePpgUserTriggerAutoActivity = 0x01,
  eventTypePpgUserTriggerBLE = 0x02,
  eventTypePpgUserTriggerUART = 0x03,
  eventTypePpgUserTriggerButtonStop = 0x04,
  eventTypePpgUserTriggerAutoActivityStop = 0x05,
  eventTypePpgUserTriggerBLEStop = 0x06,
  eventTypePpgUserTriggerUARTStop = 0x07,
  eventTypePpgUserTriggerManufacturingTestStop = 0x08,
  eventTypeSinglePress = 0x09,
  eventTypeDoublePress = 0x0a,
  eventTypeTriplePress = 0x0b,
  eventTypeLongPress = 0x0c,
  eventTypeNone = 0x0d,
  eventTypePpgWornStop = 0x0e,
  eventTypePpgTimerStop = 0x0f,
  eventTypePpgFWStop = 0x10,
  eventTypePpgFWStart = 0x11,
  eventTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, hrZoneRangeType, open) {
  hrZoneRangeTypeBelow = 0x00,
  hrZoneRangeTypeWithin = 0x01,
  hrZoneRangeTypeAbove = 0x02,
  hrZoneRangeTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, manufacturingTestType, open) {
  manufacturingTestTypeFlashIF = 0x01,
  manufacturingTestTypeFlashArray = 0x02,
  manufacturingTestTypeSpectralIF = 0x03,
  manufacturingTestTypeSpectralFIFO = 0x04,
  manufacturingTestTypeImuIF = 0x05,
  manufacturingTestTypeImuFIFO = 0x06,
  manufacturingTestTypeLed = 0x07,
  manufacturingTestTypeMotor = 0x08,
  manufacturingTestTypePpgUserTriggerButton = 0x09,
  manufacturingTestTypeSpectralLEDS = 0x0A,
  manufacturingTestTypeImuSelfTest = 0x0B,
  manufacturingTestTypeSpectralLEDLeakage = 0x0C,
  manufacturingTestTypeImuNoiseFloor = 0x0D,
  manufacturingTestTypeTemp = 0x0E,
  manufacturingTestTypePmic = 0x0F,
  manufacturingTestTypeSpectralSelfTest = 0x11,
  manufacturingTestTypeEcgRALATest = 0x12,
  manufacturingTestTypeEcgLLTest = 0x13,
  manufacturingTestTypeEcgWaveformTest = 0x14,
  manufacturingTestTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, nextPacketStatusType, open) {
  nextPacketStatusTypeSuccessful = 0x00,
  nextPacketStatusTypeBusy = 0x01,
  nextPacketStatusTypeCaughtUp = 0x02,
  nextPacketStatusTypePageEmpty = 0x03,
  nextPacketStatusTypeUnknownPacket = 0x04,
  nextPacketStatusTypeBadCommandFormat = 0x05,
  nextPacketStatusTypeBadJSON = 0xfc,
  nextPacketStatusTypeBadSDKDecode = 0xfd,
  nextPacketStatusTypeMissingDevice = 0xfe,
  nextPacketStatusTypeUnknown = 0xff,
};

SWIFT_CLASS("_TtC14SensorBioBTSDK25ppgAlgorithmConfiguration")
@interface ppgAlgorithmConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull commandString;
@end

typedef SWIFT_ENUM(uint8_t, ppgFailedType, open) {
  ppgFailedTypeWorn = 0x00,
  ppgFailedTypeStart = 0x01,
  ppgFailedTypeInterrupt = 0x02,
  ppgFailedTypeOverflow = 0x03,
  ppgFailedTypeFifoRead = 0x04,
  ppgFailedTypeAlreadyRunning = 0x05,
  ppgFailedTypeLowBattery = 0x06,
  ppgFailedTypeUserDisallowed = 0x07,
  ppgFailedTypeTimedNotWorn = 0x08,
  ppgFailedTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, ppgStatusType, open) {
  ppgStatusTypeUserContinuous = 0x00,
  ppgStatusTypeUserComplete = 0x01,
  ppgStatusTypeBackgroundComplete = 0x02,
  ppgStatusTypeBackgroundMedtor = 0x03,
  ppgStatusTypeBackgroundWornStop = 0x04,
  ppgStatusTypeBackgroundUserStop = 0x05,
  ppgStatusTypeBackgroundMotionStop = 0x06,
  ppgStatusTypeUserWornStop = 0x07,
  ppgStatusTypeUserUserStop = 0x08,
  ppgStatusTypeUserMotionStop = 0x09,
  ppgStatusTypeUserMedtorMotion = 0x0a,
  ppgStatusTypeUnknown = 0xff,
};

SWIFT_CLASS("_TtC14SensorBioBTSDK15sensrDataPacket")
@interface sensrDataPacket : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC14SensorBioBTSDK20sensrStreamingPacket")
@interface sensrStreamingPacket : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(uint8_t, sessionParameterType, open) {
  sessionParameterTypePpgCapturePeriod = 0x00,
  sessionParameterTypePpgCaptureDuration = 0x01,
  sessionParameterTypeTag = 0x10,
  sessionParameterTypeReset = 0xfd,
  sessionParameterTypeAccept = 0xfe,
  sessionParameterTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, settingsType, open) {
  settingsTypeAccelHalfRange = 0x00,
  settingsTypeGyroHalfRange = 0x01,
  settingsTypeImuSamplingRate = 0x02,
  settingsTypePpgCapturePeriod = 0x03,
  settingsTypePpgCaptureDuration = 0x04,
  settingsTypePpgSamplingRate = 0x05,
  settingsTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, streamingType, open) {
  streamingTypeHr = 0x00,
  streamingTypeHrv = 0x01,
  streamingTypeRr = 0x02,
  streamingTypeBbi = 0x03,
  streamingTypePpgSNR = 0x04,
  streamingTypePpgWave = 0x05,
  streamingTypeMotionState = 0x06,
  streamingTypePpgState = 0x07,
  streamingTypeHeartBeat = 0x08,
  streamingTypeUnknown = 0xff,
};

typedef SWIFT_ENUM(uint8_t, wavelengthType, open) {
  wavelengthTypeGreen = 0x00,
  wavelengthTypeRed = 0x01,
  wavelengthTypeIR = 0x02,
  wavelengthTypeWhiteIR = 0x03,
  wavelengthTypeWhiteWhite = 0x04,
  wavelengthTypeEcg = 0x05,
  wavelengthTypeUnknown = 0xff,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
